### ISSUE TITLE
Add in use cases

### ISSUE THREAD

**Issue by ccurtis7** [d-diaz/stand_mapping#11]
You have included a short description of the scope of your project to your README.md file. Can you also add in, whether in the README or in your documentation, a list of use cases, or some other way of describing the specific instances your code can be applied? If stumble upon your repo, it woul be nice to quickly tell the available functionality.

**Comment by d-diaz** [comment]
Core use case added to documentation on Read the Docs landing page in c029ba0a0a43ffd23a2e7d3df3de72aa7886aee6
