### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by ccurtis7** [d-diaz/stand_mapping#13]
You probably have a rough idea of the software packages you intend to use to interact with your data and do some analyses. Somewhere in your documentation, can you include a list of dependencies?

**Comment by d-diaz** [comment]
Do you want something more explicit than the environment.yml file in the root of the repo? Do you want this to be in the docs webpages?

**Comment by ccurtis7** [comment]
The ylm file is great is probably adequate come to think of it. I was just thinking that a line like [this](https://keras.io/#installation) example from Keras or [this](https://scikit-image.org/docs/stable/install.html) example from scikit-image (basically reproducing the info from the yml file into a Markdown file) would go a long way.

**Comment by aj-22** [comment]
@ccurtis7 
Addressed this issue. Added the dependencies file in the docs folder and modified index.rst as well to include dependencies section in the homepage
https://github.com/d-diaz/stand_mapping/commit/7200e5b527dba501ced26530caf75cc5a56bcdf0
