### ISSUE TITLE
Create a scoring function

### ISSUE THREAD

**Issue by d-diaz** [d-diaz/stand_mapping#17]
Add a script, `scoring.py` to `./stand_mapping/utils/`. Create functions which will enable the scoring scoring of a single-channel integer-format image with a proposed segmentation against a ground-truth segmentation. Should return a score indicating the average IOU across all segments matched to ground-truth segments. This [functions](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/utils.py) from the matterport implementation of Mask-RCNN look like a good place to start. 

If we want to use these matterport functions, we will need to implement an additional function that converts a single-channel proposed segmentation (array of shape `(W, H)` or `(W, H, 1)`) into an array of segment masks with shape `(W, H, num_segments)` where each channel in this array contains the mask for an individual segment. 

We may also need to filter the segments used for this score to focus only on forested areas (ignoring segments that are dominated by water, field, or built-up land cover types).

**Comment by OliverZhuUW** [comment]
I will use the functions mentioned above MASK_RCNN and did some research on that, as above said, we need to implement an additional function that coverts a-single proposed segmentation into an array of segment masks with space. Also, filter the unnecessary segment.

**Comment by OliverZhuUW** [comment]
In general, MASK_RCNN has four steps, first is input the image, second is extract the region proposal, third is compute CNN features, fourth is classify the region.

**Comment by OliverZhuUW** [comment]
for the next steps, we would find some reference online(github) and build our own CNN models. https://github.com/facebookresearch/Detectron
