### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by brke** [d-diaz/stand_mapping#5]
I need to learn skimage!

**Comment by d-diaz** [comment]
- [x] Add a script, `segmentation.py` to `./stand_mapping/models/` which will hold functions that ingest a multi-channel image and generate either a segmentation mask or a new image.
- [x] Add a function `seg2labels` which provides a wrapper around several `skimage.segmentation` functions. The user can provide the name of the function (e.g., 'slic', 'quickshift', 'felzenswalb') as an argument to this function, and allows additional arguments provided as keywords to be passed to that function. Returns an integer-format single-channel segmentation mask.
- [x] Add a function `seg2meancolor` which takes the same input arguments as `seg2labels`, calls `seg2labels` to perform segmentation, but also adds the additional step of computing mean-color for each segment and returns the mean-color image. Use [`skimage.color.label2rgb`](https://scikit-image.org/docs/dev/api/skimage.color.html#skimage.color.label2rgb) with the argument `kind='avg'`.

**Comment by brke** [comment]
I've written a function which allows the user to choose between slic, quickshaft, and felzenszwalb segmentation. (So far only the slic part is fully functional.)
